### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by Auhseh** [quasicodo42/HTMW#1]
@quasicodo42 Hey man, couldn't DM you on Twitter, I’ll love to take you up on this. 
https://twitter.com/Quasicodo/status/1690474856243208193?s=20

**Comment by quasicodo42** [comment]
hey, what's up?

**Comment by Auhseh** [comment]
I'm good, was referring to your request in the quoted tweet

**Comment by quasicodo42** [comment]
send me some of your work samples.

**Comment by Auhseh** [comment]
https://tryhtmw.netlify.app/

**Comment by quasicodo42** [comment]
The link is not working. I am not on here everyday. Send me an email at github@wizap.com
